vault:
  devMode: false
  port: 8200
  clusterPort: 8201
  repository: vault
  tag: 1.1.2
  pullPolicy: IfNotPresent
  volumeSize: 5Gi
  persist: false
  secretsPath: secrets/smart_city
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 10
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 10
  config:
    listener:
      tcp:
        address: '[::]:8200'
        cluster_address: '[::]:8201'
        tls_disable: true
        tls_prefer_server_cipher_suites: true
        tls_cipher_suites: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA
    storage:
      file:
        path: "/keys"
  roles:
    - name: discovery-role
      boundServiceAccounts: discovery-api
      boundServiceAccountNamespaces: discovery
      policies: s3_read
      tokenTtl: 2m
    - name: app-role
      boundServiceAccounts: reaper,andi
      boundServiceAccountNamespaces: streaming-services,admin
      policies: application
      tokenTtl: 2m
  policies:
    - name: s3_read
      path: secrets/smart_city/host_access/read
    - name: application
      path: secrets/smart_city/ingestion/*

kubectl:
  version: "1.14.0"

jq:
  version: "1.6"

ldap:
  server: bob

