apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  labels:
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.json: |
    {{ .Values.vault.config | toJson }}

  secrets.hcl: |
    path "sys/mounts/kv-v2" {
      capabilities = ["update"]
    }

    path "sys/mounts" {
      capabilities = ["read"]
    }

    path "kv-v1/*" {
      capabilities = ["create", "read", "update", "delete", "list"]
    }

    path "sys/policies/acl/*" {
      capabilities = ["create", "read", "update", "delete", "list"]
    }

    path "auth/token/create" {
      capabilities = ["create", "update", "sudo"]
    }