
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vault.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vault.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Chart.Name }}
      containers:
      - name: {{ .Chart.Name }}
        {{- if .Values.vault.devMode }}
        command: ["vault", "server", "-dev", "-dev-listen-address", "[::]:8200"]
        {{- else }}
        command: ["vault", "server", "-config", "/vault/config/config.json"]
        {{- end }}
        image: {{ .Values.vault.repository }}:{{ .Values.vault.tag }}
        imagePullPolicy: {{ .Values.vault.pullPolicy }}
        ports:
        - containerPort: {{ .Values.vault.port }} 
          name: vault
        - containerPort: {{ .Values.vault.clusterPort }}
          name: cluster-address
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: VAULT_CLUSTER_ADDR
          value: "https://$(POD_IP):8201"
        volumeMounts:
        - name: key-store
          mountPath: /keys
        - name: config 
          mountPath: /vault/config/config.json
          subPath: config.json
        - name: config
          mountPath: /vault/config/secrets.hcl
          subPath: secrets.hcl
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
      volumes:
      - name: config
        configMap:
          name: {{ .Chart.Name }}
      - name: key-store
{{- if .Values.vault.persist }}
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}
{{- else }}
        emptyDir: {}
{{- end }}