apiVersion: v1
kind: ConfigMap
metadata:
  name: init-script
  labels:
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  init.sh: |
    #!bin/sh
    apk update && apk add curl

    init_status() {
      curl http://localhost:8200/v1/sys/health | grep '"initialized":true'
    }

    sealed_status() {
      curl http://localhost:8200/v1/sys/health | grep '"sealed":false'
    }

    init_vault() {
      secrets=$(mktemp)
      trap "rm -rf ${secrets}" EXIT

      init_results=$(vault operator init | grep ':' > "${secrets}")
      keys=$(cat "${secrets}" | grep "^Unseal Key" | awk "{print \$4}")
      root_token=$(cat "${secrets}" | grep "^Initial Root Token:" | awk "{print \$4}")

      for key in $keys
      do
        echo "Unsealing vault with key"
        vault operator unseal $key
      done
    }

    init_vault