apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
spec:
  backoffLimit: 10
  activeDeadlineSeconds: 300
  template:
    spec:
      serviceAccountName: {{ .Chart.Name }}
      containers:
      - name: vault-init
        image: {{ .Values.vault.repository }}:{{ .Values.vault.tag }}
        command:
        - /bin/sh
        - -c
        - "apk add curl && \
          curl -L https://storage.googleapis.com/kubernetes-release/release/v{{ .Values.kubectl.version }}/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl && \
          curl -L https://github.com/stedolan/jq/releases/download/jq-{{ .Values.jq.version }}/jq-linux64 -o /usr/local/bin/jq && \
          chmod +x /usr/local/bin/kubectl /usr/local/bin/jq && \
          source /usr/local/bin/maintenance.sh && \
          init_vault"
        env:
        - name: VAULT_ADDR
          value: http://{{ .Chart.Name }}:{{ .Values.vault.port }}/
        volumeMounts:
        - name: maintenance-script
          mountPath: /usr/local/bin/maintenance.sh
          subPath: maintenance.sh
      volumes:
      - name: maintenance-script
        configMap:
          name: {{ .Chart.Name }}-maintenance-script
      restartPolicy: OnFailure
